#!/bin/bash

# Check if an argument is provided
if [ $# -eq 0 ]; then
  echo "Usage: rosify <package_name>"
  exit 1
fi

# Step 1: Copy the boilerplate code to the current directory
cp -r $HOME/Scripts/rosify/ros-package-boilerplates/* .

# Step 2: Call the Python script that recursively replaces occurences of package_name and PackageName with the passed argument
python $HOME/Scripts/rosify/scripts/replace_text.py "package_name" "$1"

# Step 3: Convert the package name from snake_case to CamelCase
snake_case="$1"
camel_case=$(echo "$snake_case" | sed -r 's/(^|_)([a-z])/\U\2/g')
python $HOME/Scripts/rosify/scripts/replace_text.py "PackageName" "$camel_case"

# Step 4: Call the Python script that recursively replaces folder and file names with the passed argument
python $HOME/Scripts/rosify/scripts/rename_folders_and_files.py "package_name" "$1"

# Step 5: Create a .clangd in the package's directory, so that clangd can index the package
# Create the clangd file in the package's directory
cd $1
touch .clangd
CLANGD_CONTENT="CompileFlags:
  CompilationDatabase: \"../../build\""
echo "$CLANGD_CONTENT" > .clangd
if [ -f .clangd ]; then
  echo ".clangd file created successfully with the following content:"
else
  echo "Failed to create .clangd file."
fi

cd ..

# Step 6: Give a summary of the created ROS package name
echo "===> Created a ROS package with name '$1' (the corresponding node was automatically registered as a ROS component)"
echo ""
echo "======="
echo "Summary"
echo "======="
echo "Package Name: $1"
echo "Node Name: $1_node"
